[package]
name = "rachaconta"
version = "0.1.0"
edition = "2024"
authors = ["gbPagano <guilhermebpagano@gmail.com>"]

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
petgraph = "0.8.3"
rust_decimal = { version = "1.39.0", features = ["macros"] }
